RESISC45_DIRPATH = "/Users/cristianion/Desktop/img_sat_data/NWPU-RESISC45"

RESISC45_LABELS = [
    "forest",
    "railway_station",
    "tennis_court",
    "basketball_court",
    "river",
    "storage_tank",
    "harbor",
    "terrace",
    "thermal_power_station",
    "golf_course",
    "runway",
    "roundabout",
    "bridge",
    "industrial_area",
    "baseball_diamond",
    "mobile_home_park",
    "overpass",
    "church",
    "chaparral",
    "railway",
    "stadium",
    "medium_residential",
    "sea_ice",
    "intersection",
    "lake",
    "palace",
    "airplane",
    "cloud",
    "sparse_residential",
    "airport",
    "snowberg",
    "parking_lot",
    "commercial_area",
    "rectangular_farmland",
    "island",
    "beach",
    "circular_farmland",
    "dense_residential",
    "ship",
    "mountain",
    "desert",
    "freeway",
    "meadow",
    "wetland",
    "ground_track_field",
]

UCMERCED_LANDUSE_DIRPATH = (
    "/Users/cristianion/Desktop/img_sat_data/UCMerced_LandUse/Images"
)
UCMERCED_LANDUSE_LABELS = [
    "forest",
    "buildings",
    "river",
    "mobilehomepark",
    "harbor",
    "golfcourse",
    "agricultural",
    "runway",
    "baseballdiamond",
    "overpass",
    "chaparral",
    "tenniscourt",
    "intersection",
    "airplane",
    "parkinglot",
    "sparseresidential",
    "mediumresidential",
    "denseresidential",
    "beach",
    "freeway",
    "storagetanks",
]


RESISC45_DATASET_FILE = "resisc45_dataset.csv"
UCMERCEDLU_DATASET_FILE = "ucmercedlu_dataset.csv"
