name: "model_eurosat"

model:
  location: "models/image_classification/eurosat10"
  input:
    type: image
    train:
      batch_size: 32
      file: /Users/cristianion/Desktop/img_sat_model/eurosat_dataset.csv
      folds:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      transforms:
        - resize
        - crop
        - random_horizontal_flip
        - normalize
    val:
      batch_size: 32
      file: /Users/cristianion/Desktop/img_sat_model/eurosat_dataset.csv
      folds:
        - 6
        - 7
      transforms:
        - resize
        - crop
        - normalize
    test:
      batch_size: 32
      file: /Users/cristianion/Desktop/img_sat_model/eurosat_dataset.csv
      folds:
        - 8
        - 9
      transforms:
        - resize
        - crop
        - normalize
  output:
    num_classes: 10
    probability: softmax
    criterion: mse
    val_metrics:
      error_rate: true
      mse: true
    labels:
      - AnnualCrop
      - Forest
      - HerbaceousVegetation
      - Highway
      - Industrial
      - Pasture
      - PermanentCrop
      - Residential
      - River
      - SeaLake
  cnn:
    optimizer:
      type: sgd
      lr: 0.01
      momentum: 0.9
    num_epochs: 20
    weights_init: imagenet
    architecture: resnet50
