name: "model_ucm21"

model:
  location: "imgcls/models/v1"
  input:
    type: image
    train:
      batch_size: 32
      file: /Users/cristianion/Desktop/satimg_model/ucmercedlu_dataset.csv
      folds:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      transforms:
        - resize
        - crop
        - random_horizontal_flip
        - normalize
    val:
      batch_size: 32
      file: /Users/cristianion/Desktop/satimg_model/ucmercedlu_dataset.csv
      folds:
        - 6
        - 7
      transforms:
        - resize
        - crop
        - normalize
    test:
      batch_size: 32
      file: /Users/cristianion/Desktop/satimg_model/ucmercedlu_dataset.csv
      folds:
        - 8
        - 9
      transforms:
        - resize
        - crop
        - normalize
  output:
    num_classes: 21
    probability: softmax
    criterion: mse
    val_metrics:
      error_rate: true
      mse: true
    labels:
      - forest
      - buildings
      - river
      - mobilehomepark
      - harbor
      - golfcourse
      - agricultural
      - runway
      - baseballdiamond
      - overpass
      - chaparral
      - tenniscourt
      - intersection
      - airplane
      - parkinglot
      - sparseresidential
      - mediumresidential
      - denseresidential
      - beach
      - freeway
      - storagetanks
  cnn:
    optimizer:
      type: sgd
      lr: 0.01
      momentum: 0.9
    num_epochs: 20
    weights_init: imagenet
    architecture: resnet50
